// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Organization.Application.Modules.Infrastructures.Entity;

public partial class TOrganization
{
    public decimal Id { get; set; }

    public Guid Identifier { get; set; }

    public string Name { get; set; }

    public int OrgType { get; set; }

    public bool Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public byte[] Version { get; set; }
}