// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Organization.Application.Modules.Infrastructures.Entity;

namespace Organization.Application.Modules.Infrastructures;

public partial class OrganizationContext : DbContext
{
    public OrganizationContext(DbContextOptions<OrganizationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TOrganization> TOrganizations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TOrganization>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3214EC07F0CD2EEB");

            entity.ToTable("TOrganization", "OrgSchema");

            entity.HasIndex(e => e.Identifier, "idx_Identifier_Organization").IsUnique();

            entity.HasIndex(e => e.Name, "idx_Name_Organization").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnType("numeric(18, 0)");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Version)
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}